### ISSUE TITLE
getGlobalEvents displays only logged in user

### ISSUE THREAD

**Issue by alexlavr** [netvlies/basecamp-php#29]
Trying to use `getGlobalEvents` API but it's returning just my events, not any activity of other members working on the projects. Is there a way to display all activity? Thanks.

**Comment by ricbra** [comment]
Take a look at https://github.com/basecamp/bcx-api/blob/master/sections/events.md where this call is described. I believe this is the way the API behaves, not something that's wrong in our implementation. 

I've not used the Basecamp API since a long time, so I'm afraid you have to dig through the API docs for your answer.
